name: Lint
on:
  push:
    branches: main
  pull_request:

jobs:
  tflint:
    runs-on: ubuntu-latest



    steps:
    - uses: actions/checkout@v2
      name: Checkout source code

    - uses: actions/cache@v2
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}
    
    - name: Setup TFLint
      # You may pin to the exact commit or the version.
      # uses: terraform-linters/setup-tflint@ba6bb2989f94daf58a4cc6eac2c1ca7398a678bf
      uses: terraform-linters/setup-tflint@v3.0.0
      with:
         # TFLint version to install
         tflint_version: default




    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact
